[project]
name = "sample-python"
version = "0.0.1"
description = "We provide a sample app using Python that you can deploy on App Platform"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "requests",
    "httpx"
]
